### PR TITLE
Creating the input interface for submitting the bugs / feedback in sidebar-left.tpl - User Story 2

### LINKED ISSUE #16: Creating the input interface for submitting the bugs / feedback - User Story 2
Accepting Criteria: 
- Users be able to navigate the submission and type a comment 
- The button should open a simple, user-friendly form that should include fields for title and description.
- Users be able to locate where to submit these comments 
- The form submission should trigger an automated confirmation/acknowledgment message to the user.
- The feedback/bug report should be saved and accessible to administrators for review.

### PR DESCRIPTION
**Pull request by galishaq**
Creating the input interface for submitting the bugs / feedback.
made sure that bugs/feedbacks can be submitted.
ensured that an acknoldegment/ confirmation notice message shows up after file is submitted
ensured that the text disappears when bug/feedback is submitted
made some interface stylistic changes.
ensured that the submit bug/feedback button works properly
resolves #16

### CODE REVIEW

**Comment by galishaq** [comment]
resolves #16

**Review by zanzoonh — APPROVED** [review]
Looks great to me!

**Comment by AlAnoud2003** [comment]
The code looks good!

**Review by AlAnoud2003 — APPROVED** [review]
The code looks good!

**Pull request merged**
